" configure vim to look in the bundles folder
set runtimepath^=~/.vim/bundle/vim-gitgutter

" I need to settle on a colour scheme
" colorscheme

" syntax highlighting
syntax enable 

" incremental search
set incsearch
" highlight all search results
set hlsearch

" auto indent new lines
set autoindent

" the number of spaces to show for a tab
set tabstop=4
" the number of spaces to use for a tab when editing
set softtabstop=4
" use spaces for tabs in edit mode
set expandtab

" show line numbers
set number

" set my own key to move to command mode
inoremap rty <esc>
inoremap <esc> <Nopt

" Automatically correct common typing mistakes I make
abbr ther the

" configuration for git changes plugin
set updatetime=250

